db:
  url: "jdbc:postgresql://localhost:15432/ironbank"
  username: "postgres"
  password: "1234"

cache:
  type: "lfu"
  poolSize: 3

pdf:
  output: "build/tmp/document.pdf"
  layer: "src/main/resources/Clevertec_Template.pdf"
